before_script:
    - apt-get update -qq && apt-get -y -qq install build-essential yasm grub-common grub-pc-bin xorriso
    - gcc --version
    - yasm --version
    - make -v

stages:
    - package

package:
    stage: package
    script:
    - make iso
    artifacts:
        paths:
        - hypov.iso
        - hypov.bin
        - HypoV.map
        - sys/core/hvcore.elf64
        - sys/core/hvcore.elf64.xz
