before_script:
    - apt-get update -qq && apt-get -y -qq install build-essential nasm grub-common xorriso
    - gcc --version
    - nasm -v
    - make -v

stages:
    - build
    - package

build_job:
    stage: build
    script:
    - make
    only:
    - master

package:
    stage: package
    script:
    - make iso
    artifacts:
        paths:
        - hypov.iso
