before_script:
    - apt-get update -qq && apt-get -y -qq install build-essential nasm
    - gcc --version
    - nasm -v
    - make -v

stages:
    - build

build_job:
    stage: build
    script:
        - make
    only:
        - master

