before_script:
    - apt-get update -qq && apt-get -y -qq install build-essential nasm grub-common
    - gcc --version
    - nasm -v
    - make -v

stages:
    - build
    - isogen

build_job:
    stage: build
    script:
        - make
    only:
        - master

isogen_job:
    stage: isogen
    script:
        - make iso
    only:
        - master
