before_script:
    - apt-get update -qq && apt-get -y -qq install build-essential nasm grub-common xorriso
    - gcc --version
    - nasm -v
    - make -v

stages:
    - package

package:
    stage: package
    script:
    - make iso
    artifacts:
        paths:
        - hypov.iso
        - hypov.bin
        - HypoV.map
