#obj-$(CONFIG_XZ_DEC)        += xz_dec.o
obj-$(CONFIG_XZ_DEC)        += xz_dec_stream.o xz_dec_lzma2.o xz_crc32.o
obj-$(CONFIG_XZ_DEC_BCJ)    += xz_dec_bcj.o
#obj-$(CONFIG_XZ_DEC_TEST)   += xz_dec_test.o
