# XXX: This file works differently, than the usual subdir Makefiles.
# This will be included per each architecture library Makefile in lib32/ and lib64
# the object file and library archive will be built there. To make this possible
# the sources are referenced from there to here with symbolic links.
#
# This is a very ugly hack.

lib-y += print.o
lib-y += string.o

lib-y += drivers/video/pc_console.o
lib-y += drivers/char_display.o
