; Assembly wrapper subroutines for all possible interrupts
; Automatically generated by scripts/scripts/intgen.rb, at Wed Jun  3 22:05:19 2026
; DO NOT MODIFY!

extern __int_handler

section .text

global __int_handle_0
__int_handle_0:
    push 0x0
    push 0
    jmp __int_handler

global __int_handle_1
__int_handle_1:
    push 0x0
    push 1
    jmp __int_handler

global __int_handle_2
__int_handle_2:
    push 0x0
    push 2
    jmp __int_handler

global __int_handle_3
__int_handle_3:
    push 0x0
    push 3
    jmp __int_handler

global __int_handle_4
__int_handle_4:
    push 0x0
    push 4
    jmp __int_handler

global __int_handle_5
__int_handle_5:
    push 0x0
    push 5
    jmp __int_handler

global __int_handle_6
__int_handle_6:
    push 0x0
    push 6
    jmp __int_handler

global __int_handle_7
__int_handle_7:
    push 0x0
    push 7
    jmp __int_handler

global __int_handle_8
__int_handle_8:
    push 8
    jmp __int_handler

global __int_handle_9
__int_handle_9:
    push 0x0
    push 9
    jmp __int_handler

global __int_handle_10
__int_handle_10:
    push 10
    jmp __int_handler

global __int_handle_11
__int_handle_11:
    push 11
    jmp __int_handler

global __int_handle_12
__int_handle_12:
    push 12
    jmp __int_handler

global __int_handle_13
__int_handle_13:
    push 13
    jmp __int_handler

global __int_handle_14
__int_handle_14:
    push 14
    jmp __int_handler

global __int_handle_15
__int_handle_15:
    push 0x0
    push 15
    jmp __int_handler

global __int_handle_16
__int_handle_16:
    push 0x0
    push 16
    jmp __int_handler

global __int_handle_17
__int_handle_17:
    push 17
    jmp __int_handler

global __int_handle_18
__int_handle_18:
    push 0x0
    push 18
    jmp __int_handler

global __int_handle_19
__int_handle_19:
    push 0x0
    push 19
    jmp __int_handler

global __int_handle_20
__int_handle_20:
    push 0x0
    push 20
    jmp __int_handler

global __int_handle_21
__int_handle_21:
    push 0x0
    push 21
    jmp __int_handler

global __int_handle_22
__int_handle_22:
    push 0x0
    push 22
    jmp __int_handler

global __int_handle_23
__int_handle_23:
    push 0x0
    push 23
    jmp __int_handler

global __int_handle_24
__int_handle_24:
    push 0x0
    push 24
    jmp __int_handler

global __int_handle_25
__int_handle_25:
    push 0x0
    push 25
    jmp __int_handler

global __int_handle_26
__int_handle_26:
    push 0x0
    push 26
    jmp __int_handler

global __int_handle_27
__int_handle_27:
    push 0x0
    push 27
    jmp __int_handler

global __int_handle_28
__int_handle_28:
    push 0x0
    push 28
    jmp __int_handler

global __int_handle_29
__int_handle_29:
    push 0x0
    push 29
    jmp __int_handler

global __int_handle_30
__int_handle_30:
    push 0x0
    push 30
    jmp __int_handler

global __int_handle_31
__int_handle_31:
    push 0x0
    push 31
    jmp __int_handler

global __int_handle_32
__int_handle_32:
    push 0x0
    push 32
    jmp __int_handler

global __int_handle_33
__int_handle_33:
    push 0x0
    push 33
    jmp __int_handler

global __int_handle_34
__int_handle_34:
    push 0x0
    push 34
    jmp __int_handler

global __int_handle_35
__int_handle_35:
    push 0x0
    push 35
    jmp __int_handler

global __int_handle_36
__int_handle_36:
    push 0x0
    push 36
    jmp __int_handler

global __int_handle_37
__int_handle_37:
    push 0x0
    push 37
    jmp __int_handler

global __int_handle_38
__int_handle_38:
    push 0x0
    push 38
    jmp __int_handler

global __int_handle_39
__int_handle_39:
    push 0x0
    push 39
    jmp __int_handler

global __int_handle_40
__int_handle_40:
    push 0x0
    push 40
    jmp __int_handler

global __int_handle_41
__int_handle_41:
    push 0x0
    push 41
    jmp __int_handler

global __int_handle_42
__int_handle_42:
    push 0x0
    push 42
    jmp __int_handler

global __int_handle_43
__int_handle_43:
    push 0x0
    push 43
    jmp __int_handler

global __int_handle_44
__int_handle_44:
    push 0x0
    push 44
    jmp __int_handler

global __int_handle_45
__int_handle_45:
    push 0x0
    push 45
    jmp __int_handler

global __int_handle_46
__int_handle_46:
    push 0x0
    push 46
    jmp __int_handler

global __int_handle_47
__int_handle_47:
    push 0x0
    push 47
    jmp __int_handler

global __int_handle_48
__int_handle_48:
    push 0x0
    push 48
    jmp __int_handler

global __int_handle_49
__int_handle_49:
    push 0x0
    push 49
    jmp __int_handler

global __int_handle_50
__int_handle_50:
    push 0x0
    push 50
    jmp __int_handler

global __int_handle_51
__int_handle_51:
    push 0x0
    push 51
    jmp __int_handler

global __int_handle_52
__int_handle_52:
    push 0x0
    push 52
    jmp __int_handler

global __int_handle_53
__int_handle_53:
    push 0x0
    push 53
    jmp __int_handler

global __int_handle_54
__int_handle_54:
    push 0x0
    push 54
    jmp __int_handler

global __int_handle_55
__int_handle_55:
    push 0x0
    push 55
    jmp __int_handler

global __int_handle_56
__int_handle_56:
    push 0x0
    push 56
    jmp __int_handler

global __int_handle_57
__int_handle_57:
    push 0x0
    push 57
    jmp __int_handler

global __int_handle_58
__int_handle_58:
    push 0x0
    push 58
    jmp __int_handler

global __int_handle_59
__int_handle_59:
    push 0x0
    push 59
    jmp __int_handler

global __int_handle_60
__int_handle_60:
    push 0x0
    push 60
    jmp __int_handler

global __int_handle_61
__int_handle_61:
    push 0x0
    push 61
    jmp __int_handler

global __int_handle_62
__int_handle_62:
    push 0x0
    push 62
    jmp __int_handler

global __int_handle_63
__int_handle_63:
    push 0x0
    push 63
    jmp __int_handler

global __int_handle_64
__int_handle_64:
    push 0x0
    push 64
    jmp __int_handler

global __int_handle_65
__int_handle_65:
    push 0x0
    push 65
    jmp __int_handler

global __int_handle_66
__int_handle_66:
    push 0x0
    push 66
    jmp __int_handler

global __int_handle_67
__int_handle_67:
    push 0x0
    push 67
    jmp __int_handler

global __int_handle_68
__int_handle_68:
    push 0x0
    push 68
    jmp __int_handler

global __int_handle_69
__int_handle_69:
    push 0x0
    push 69
    jmp __int_handler

global __int_handle_70
__int_handle_70:
    push 0x0
    push 70
    jmp __int_handler

global __int_handle_71
__int_handle_71:
    push 0x0
    push 71
    jmp __int_handler

global __int_handle_72
__int_handle_72:
    push 0x0
    push 72
    jmp __int_handler

global __int_handle_73
__int_handle_73:
    push 0x0
    push 73
    jmp __int_handler

global __int_handle_74
__int_handle_74:
    push 0x0
    push 74
    jmp __int_handler

global __int_handle_75
__int_handle_75:
    push 0x0
    push 75
    jmp __int_handler

global __int_handle_76
__int_handle_76:
    push 0x0
    push 76
    jmp __int_handler

global __int_handle_77
__int_handle_77:
    push 0x0
    push 77
    jmp __int_handler

global __int_handle_78
__int_handle_78:
    push 0x0
    push 78
    jmp __int_handler

global __int_handle_79
__int_handle_79:
    push 0x0
    push 79
    jmp __int_handler

global __int_handle_80
__int_handle_80:
    push 0x0
    push 80
    jmp __int_handler

global __int_handle_81
__int_handle_81:
    push 0x0
    push 81
    jmp __int_handler

global __int_handle_82
__int_handle_82:
    push 0x0
    push 82
    jmp __int_handler

global __int_handle_83
__int_handle_83:
    push 0x0
    push 83
    jmp __int_handler

global __int_handle_84
__int_handle_84:
    push 0x0
    push 84
    jmp __int_handler

global __int_handle_85
__int_handle_85:
    push 0x0
    push 85
    jmp __int_handler

global __int_handle_86
__int_handle_86:
    push 0x0
    push 86
    jmp __int_handler

global __int_handle_87
__int_handle_87:
    push 0x0
    push 87
    jmp __int_handler

global __int_handle_88
__int_handle_88:
    push 0x0
    push 88
    jmp __int_handler

global __int_handle_89
__int_handle_89:
    push 0x0
    push 89
    jmp __int_handler

global __int_handle_90
__int_handle_90:
    push 0x0
    push 90
    jmp __int_handler

global __int_handle_91
__int_handle_91:
    push 0x0
    push 91
    jmp __int_handler

global __int_handle_92
__int_handle_92:
    push 0x0
    push 92
    jmp __int_handler

global __int_handle_93
__int_handle_93:
    push 0x0
    push 93
    jmp __int_handler

global __int_handle_94
__int_handle_94:
    push 0x0
    push 94
    jmp __int_handler

global __int_handle_95
__int_handle_95:
    push 0x0
    push 95
    jmp __int_handler

global __int_handle_96
__int_handle_96:
    push 0x0
    push 96
    jmp __int_handler

global __int_handle_97
__int_handle_97:
    push 0x0
    push 97
    jmp __int_handler

global __int_handle_98
__int_handle_98:
    push 0x0
    push 98
    jmp __int_handler

global __int_handle_99
__int_handle_99:
    push 0x0
    push 99
    jmp __int_handler

global __int_handle_100
__int_handle_100:
    push 0x0
    push 100
    jmp __int_handler

global __int_handle_101
__int_handle_101:
    push 0x0
    push 101
    jmp __int_handler

global __int_handle_102
__int_handle_102:
    push 0x0
    push 102
    jmp __int_handler

global __int_handle_103
__int_handle_103:
    push 0x0
    push 103
    jmp __int_handler

global __int_handle_104
__int_handle_104:
    push 0x0
    push 104
    jmp __int_handler

global __int_handle_105
__int_handle_105:
    push 0x0
    push 105
    jmp __int_handler

global __int_handle_106
__int_handle_106:
    push 0x0
    push 106
    jmp __int_handler

global __int_handle_107
__int_handle_107:
    push 0x0
    push 107
    jmp __int_handler

global __int_handle_108
__int_handle_108:
    push 0x0
    push 108
    jmp __int_handler

global __int_handle_109
__int_handle_109:
    push 0x0
    push 109
    jmp __int_handler

global __int_handle_110
__int_handle_110:
    push 0x0
    push 110
    jmp __int_handler

global __int_handle_111
__int_handle_111:
    push 0x0
    push 111
    jmp __int_handler

global __int_handle_112
__int_handle_112:
    push 0x0
    push 112
    jmp __int_handler

global __int_handle_113
__int_handle_113:
    push 0x0
    push 113
    jmp __int_handler

global __int_handle_114
__int_handle_114:
    push 0x0
    push 114
    jmp __int_handler

global __int_handle_115
__int_handle_115:
    push 0x0
    push 115
    jmp __int_handler

global __int_handle_116
__int_handle_116:
    push 0x0
    push 116
    jmp __int_handler

global __int_handle_117
__int_handle_117:
    push 0x0
    push 117
    jmp __int_handler

global __int_handle_118
__int_handle_118:
    push 0x0
    push 118
    jmp __int_handler

global __int_handle_119
__int_handle_119:
    push 0x0
    push 119
    jmp __int_handler

global __int_handle_120
__int_handle_120:
    push 0x0
    push 120
    jmp __int_handler

global __int_handle_121
__int_handle_121:
    push 0x0
    push 121
    jmp __int_handler

global __int_handle_122
__int_handle_122:
    push 0x0
    push 122
    jmp __int_handler

global __int_handle_123
__int_handle_123:
    push 0x0
    push 123
    jmp __int_handler

global __int_handle_124
__int_handle_124:
    push 0x0
    push 124
    jmp __int_handler

global __int_handle_125
__int_handle_125:
    push 0x0
    push 125
    jmp __int_handler

global __int_handle_126
__int_handle_126:
    push 0x0
    push 126
    jmp __int_handler

global __int_handle_127
__int_handle_127:
    push 0x0
    push 127
    jmp __int_handler

global __int_handle_128
__int_handle_128:
    push 0x0
    push 128
    jmp __int_handler

global __int_handle_129
__int_handle_129:
    push 0x0
    push 129
    jmp __int_handler

global __int_handle_130
__int_handle_130:
    push 0x0
    push 130
    jmp __int_handler

global __int_handle_131
__int_handle_131:
    push 0x0
    push 131
    jmp __int_handler

global __int_handle_132
__int_handle_132:
    push 0x0
    push 132
    jmp __int_handler

global __int_handle_133
__int_handle_133:
    push 0x0
    push 133
    jmp __int_handler

global __int_handle_134
__int_handle_134:
    push 0x0
    push 134
    jmp __int_handler

global __int_handle_135
__int_handle_135:
    push 0x0
    push 135
    jmp __int_handler

global __int_handle_136
__int_handle_136:
    push 0x0
    push 136
    jmp __int_handler

global __int_handle_137
__int_handle_137:
    push 0x0
    push 137
    jmp __int_handler

global __int_handle_138
__int_handle_138:
    push 0x0
    push 138
    jmp __int_handler

global __int_handle_139
__int_handle_139:
    push 0x0
    push 139
    jmp __int_handler

global __int_handle_140
__int_handle_140:
    push 0x0
    push 140
    jmp __int_handler

global __int_handle_141
__int_handle_141:
    push 0x0
    push 141
    jmp __int_handler

global __int_handle_142
__int_handle_142:
    push 0x0
    push 142
    jmp __int_handler

global __int_handle_143
__int_handle_143:
    push 0x0
    push 143
    jmp __int_handler

global __int_handle_144
__int_handle_144:
    push 0x0
    push 144
    jmp __int_handler

global __int_handle_145
__int_handle_145:
    push 0x0
    push 145
    jmp __int_handler

global __int_handle_146
__int_handle_146:
    push 0x0
    push 146
    jmp __int_handler

global __int_handle_147
__int_handle_147:
    push 0x0
    push 147
    jmp __int_handler

global __int_handle_148
__int_handle_148:
    push 0x0
    push 148
    jmp __int_handler

global __int_handle_149
__int_handle_149:
    push 0x0
    push 149
    jmp __int_handler

global __int_handle_150
__int_handle_150:
    push 0x0
    push 150
    jmp __int_handler

global __int_handle_151
__int_handle_151:
    push 0x0
    push 151
    jmp __int_handler

global __int_handle_152
__int_handle_152:
    push 0x0
    push 152
    jmp __int_handler

global __int_handle_153
__int_handle_153:
    push 0x0
    push 153
    jmp __int_handler

global __int_handle_154
__int_handle_154:
    push 0x0
    push 154
    jmp __int_handler

global __int_handle_155
__int_handle_155:
    push 0x0
    push 155
    jmp __int_handler

global __int_handle_156
__int_handle_156:
    push 0x0
    push 156
    jmp __int_handler

global __int_handle_157
__int_handle_157:
    push 0x0
    push 157
    jmp __int_handler

global __int_handle_158
__int_handle_158:
    push 0x0
    push 158
    jmp __int_handler

global __int_handle_159
__int_handle_159:
    push 0x0
    push 159
    jmp __int_handler

global __int_handle_160
__int_handle_160:
    push 0x0
    push 160
    jmp __int_handler

global __int_handle_161
__int_handle_161:
    push 0x0
    push 161
    jmp __int_handler

global __int_handle_162
__int_handle_162:
    push 0x0
    push 162
    jmp __int_handler

global __int_handle_163
__int_handle_163:
    push 0x0
    push 163
    jmp __int_handler

global __int_handle_164
__int_handle_164:
    push 0x0
    push 164
    jmp __int_handler

global __int_handle_165
__int_handle_165:
    push 0x0
    push 165
    jmp __int_handler

global __int_handle_166
__int_handle_166:
    push 0x0
    push 166
    jmp __int_handler

global __int_handle_167
__int_handle_167:
    push 0x0
    push 167
    jmp __int_handler

global __int_handle_168
__int_handle_168:
    push 0x0
    push 168
    jmp __int_handler

global __int_handle_169
__int_handle_169:
    push 0x0
    push 169
    jmp __int_handler

global __int_handle_170
__int_handle_170:
    push 0x0
    push 170
    jmp __int_handler

global __int_handle_171
__int_handle_171:
    push 0x0
    push 171
    jmp __int_handler

global __int_handle_172
__int_handle_172:
    push 0x0
    push 172
    jmp __int_handler

global __int_handle_173
__int_handle_173:
    push 0x0
    push 173
    jmp __int_handler

global __int_handle_174
__int_handle_174:
    push 0x0
    push 174
    jmp __int_handler

global __int_handle_175
__int_handle_175:
    push 0x0
    push 175
    jmp __int_handler

global __int_handle_176
__int_handle_176:
    push 0x0
    push 176
    jmp __int_handler

global __int_handle_177
__int_handle_177:
    push 0x0
    push 177
    jmp __int_handler

global __int_handle_178
__int_handle_178:
    push 0x0
    push 178
    jmp __int_handler

global __int_handle_179
__int_handle_179:
    push 0x0
    push 179
    jmp __int_handler

global __int_handle_180
__int_handle_180:
    push 0x0
    push 180
    jmp __int_handler

global __int_handle_181
__int_handle_181:
    push 0x0
    push 181
    jmp __int_handler

global __int_handle_182
__int_handle_182:
    push 0x0
    push 182
    jmp __int_handler

global __int_handle_183
__int_handle_183:
    push 0x0
    push 183
    jmp __int_handler

global __int_handle_184
__int_handle_184:
    push 0x0
    push 184
    jmp __int_handler

global __int_handle_185
__int_handle_185:
    push 0x0
    push 185
    jmp __int_handler

global __int_handle_186
__int_handle_186:
    push 0x0
    push 186
    jmp __int_handler

global __int_handle_187
__int_handle_187:
    push 0x0
    push 187
    jmp __int_handler

global __int_handle_188
__int_handle_188:
    push 0x0
    push 188
    jmp __int_handler

global __int_handle_189
__int_handle_189:
    push 0x0
    push 189
    jmp __int_handler

global __int_handle_190
__int_handle_190:
    push 0x0
    push 190
    jmp __int_handler

global __int_handle_191
__int_handle_191:
    push 0x0
    push 191
    jmp __int_handler

global __int_handle_192
__int_handle_192:
    push 0x0
    push 192
    jmp __int_handler

global __int_handle_193
__int_handle_193:
    push 0x0
    push 193
    jmp __int_handler

global __int_handle_194
__int_handle_194:
    push 0x0
    push 194
    jmp __int_handler

global __int_handle_195
__int_handle_195:
    push 0x0
    push 195
    jmp __int_handler

global __int_handle_196
__int_handle_196:
    push 0x0
    push 196
    jmp __int_handler

global __int_handle_197
__int_handle_197:
    push 0x0
    push 197
    jmp __int_handler

global __int_handle_198
__int_handle_198:
    push 0x0
    push 198
    jmp __int_handler

global __int_handle_199
__int_handle_199:
    push 0x0
    push 199
    jmp __int_handler

global __int_handle_200
__int_handle_200:
    push 0x0
    push 200
    jmp __int_handler

global __int_handle_201
__int_handle_201:
    push 0x0
    push 201
    jmp __int_handler

global __int_handle_202
__int_handle_202:
    push 0x0
    push 202
    jmp __int_handler

global __int_handle_203
__int_handle_203:
    push 0x0
    push 203
    jmp __int_handler

global __int_handle_204
__int_handle_204:
    push 0x0
    push 204
    jmp __int_handler

global __int_handle_205
__int_handle_205:
    push 0x0
    push 205
    jmp __int_handler

global __int_handle_206
__int_handle_206:
    push 0x0
    push 206
    jmp __int_handler

global __int_handle_207
__int_handle_207:
    push 0x0
    push 207
    jmp __int_handler

global __int_handle_208
__int_handle_208:
    push 0x0
    push 208
    jmp __int_handler

global __int_handle_209
__int_handle_209:
    push 0x0
    push 209
    jmp __int_handler

global __int_handle_210
__int_handle_210:
    push 0x0
    push 210
    jmp __int_handler

global __int_handle_211
__int_handle_211:
    push 0x0
    push 211
    jmp __int_handler

global __int_handle_212
__int_handle_212:
    push 0x0
    push 212
    jmp __int_handler

global __int_handle_213
__int_handle_213:
    push 0x0
    push 213
    jmp __int_handler

global __int_handle_214
__int_handle_214:
    push 0x0
    push 214
    jmp __int_handler

global __int_handle_215
__int_handle_215:
    push 0x0
    push 215
    jmp __int_handler

global __int_handle_216
__int_handle_216:
    push 0x0
    push 216
    jmp __int_handler

global __int_handle_217
__int_handle_217:
    push 0x0
    push 217
    jmp __int_handler

global __int_handle_218
__int_handle_218:
    push 0x0
    push 218
    jmp __int_handler

global __int_handle_219
__int_handle_219:
    push 0x0
    push 219
    jmp __int_handler

global __int_handle_220
__int_handle_220:
    push 0x0
    push 220
    jmp __int_handler

global __int_handle_221
__int_handle_221:
    push 0x0
    push 221
    jmp __int_handler

global __int_handle_222
__int_handle_222:
    push 0x0
    push 222
    jmp __int_handler

global __int_handle_223
__int_handle_223:
    push 0x0
    push 223
    jmp __int_handler

global __int_handle_224
__int_handle_224:
    push 0x0
    push 224
    jmp __int_handler

global __int_handle_225
__int_handle_225:
    push 0x0
    push 225
    jmp __int_handler

global __int_handle_226
__int_handle_226:
    push 0x0
    push 226
    jmp __int_handler

global __int_handle_227
__int_handle_227:
    push 0x0
    push 227
    jmp __int_handler

global __int_handle_228
__int_handle_228:
    push 0x0
    push 228
    jmp __int_handler

global __int_handle_229
__int_handle_229:
    push 0x0
    push 229
    jmp __int_handler

global __int_handle_230
__int_handle_230:
    push 0x0
    push 230
    jmp __int_handler

global __int_handle_231
__int_handle_231:
    push 0x0
    push 231
    jmp __int_handler

global __int_handle_232
__int_handle_232:
    push 0x0
    push 232
    jmp __int_handler

global __int_handle_233
__int_handle_233:
    push 0x0
    push 233
    jmp __int_handler

global __int_handle_234
__int_handle_234:
    push 0x0
    push 234
    jmp __int_handler

global __int_handle_235
__int_handle_235:
    push 0x0
    push 235
    jmp __int_handler

global __int_handle_236
__int_handle_236:
    push 0x0
    push 236
    jmp __int_handler

global __int_handle_237
__int_handle_237:
    push 0x0
    push 237
    jmp __int_handler

global __int_handle_238
__int_handle_238:
    push 0x0
    push 238
    jmp __int_handler

global __int_handle_239
__int_handle_239:
    push 0x0
    push 239
    jmp __int_handler

global __int_handle_240
__int_handle_240:
    push 0x0
    push 240
    jmp __int_handler

global __int_handle_241
__int_handle_241:
    push 0x0
    push 241
    jmp __int_handler

global __int_handle_242
__int_handle_242:
    push 0x0
    push 242
    jmp __int_handler

global __int_handle_243
__int_handle_243:
    push 0x0
    push 243
    jmp __int_handler

global __int_handle_244
__int_handle_244:
    push 0x0
    push 244
    jmp __int_handler

global __int_handle_245
__int_handle_245:
    push 0x0
    push 245
    jmp __int_handler

global __int_handle_246
__int_handle_246:
    push 0x0
    push 246
    jmp __int_handler

global __int_handle_247
__int_handle_247:
    push 0x0
    push 247
    jmp __int_handler

global __int_handle_248
__int_handle_248:
    push 0x0
    push 248
    jmp __int_handler

global __int_handle_249
__int_handle_249:
    push 0x0
    push 249
    jmp __int_handler

global __int_handle_250
__int_handle_250:
    push 0x0
    push 250
    jmp __int_handler

global __int_handle_251
__int_handle_251:
    push 0x0
    push 251
    jmp __int_handler

global __int_handle_252
__int_handle_252:
    push 0x0
    push 252
    jmp __int_handler

global __int_handle_253
__int_handle_253:
    push 0x0
    push 253
    jmp __int_handler

global __int_handle_254
__int_handle_254:
    push 0x0
    push 254
    jmp __int_handler

global __int_handle_255
__int_handle_255:
    push 0x0
    push 255
    jmp __int_handler

section .rodata
global __int_vector
__int_vector:
    dq __int_handle_0
    dq __int_handle_1
    dq __int_handle_2
    dq __int_handle_3
    dq __int_handle_4
    dq __int_handle_5
    dq __int_handle_6
    dq __int_handle_7
    dq __int_handle_8
    dq __int_handle_9
    dq __int_handle_10
    dq __int_handle_11
    dq __int_handle_12
    dq __int_handle_13
    dq __int_handle_14
    dq __int_handle_15
    dq __int_handle_16
    dq __int_handle_17
    dq __int_handle_18
    dq __int_handle_19
    dq __int_handle_20
    dq __int_handle_21
    dq __int_handle_22
    dq __int_handle_23
    dq __int_handle_24
    dq __int_handle_25
    dq __int_handle_26
    dq __int_handle_27
    dq __int_handle_28
    dq __int_handle_29
    dq __int_handle_30
    dq __int_handle_31
    dq __int_handle_32
    dq __int_handle_33
    dq __int_handle_34
    dq __int_handle_35
    dq __int_handle_36
    dq __int_handle_37
    dq __int_handle_38
    dq __int_handle_39
    dq __int_handle_40
    dq __int_handle_41
    dq __int_handle_42
    dq __int_handle_43
    dq __int_handle_44
    dq __int_handle_45
    dq __int_handle_46
    dq __int_handle_47
    dq __int_handle_48
    dq __int_handle_49
    dq __int_handle_50
    dq __int_handle_51
    dq __int_handle_52
    dq __int_handle_53
    dq __int_handle_54
    dq __int_handle_55
    dq __int_handle_56
    dq __int_handle_57
    dq __int_handle_58
    dq __int_handle_59
    dq __int_handle_60
    dq __int_handle_61
    dq __int_handle_62
    dq __int_handle_63
    dq __int_handle_64
    dq __int_handle_65
    dq __int_handle_66
    dq __int_handle_67
    dq __int_handle_68
    dq __int_handle_69
    dq __int_handle_70
    dq __int_handle_71
    dq __int_handle_72
    dq __int_handle_73
    dq __int_handle_74
    dq __int_handle_75
    dq __int_handle_76
    dq __int_handle_77
    dq __int_handle_78
    dq __int_handle_79
    dq __int_handle_80
    dq __int_handle_81
    dq __int_handle_82
    dq __int_handle_83
    dq __int_handle_84
    dq __int_handle_85
    dq __int_handle_86
    dq __int_handle_87
    dq __int_handle_88
    dq __int_handle_89
    dq __int_handle_90
    dq __int_handle_91
    dq __int_handle_92
    dq __int_handle_93
    dq __int_handle_94
    dq __int_handle_95
    dq __int_handle_96
    dq __int_handle_97
    dq __int_handle_98
    dq __int_handle_99
    dq __int_handle_100
    dq __int_handle_101
    dq __int_handle_102
    dq __int_handle_103
    dq __int_handle_104
    dq __int_handle_105
    dq __int_handle_106
    dq __int_handle_107
    dq __int_handle_108
    dq __int_handle_109
    dq __int_handle_110
    dq __int_handle_111
    dq __int_handle_112
    dq __int_handle_113
    dq __int_handle_114
    dq __int_handle_115
    dq __int_handle_116
    dq __int_handle_117
    dq __int_handle_118
    dq __int_handle_119
    dq __int_handle_120
    dq __int_handle_121
    dq __int_handle_122
    dq __int_handle_123
    dq __int_handle_124
    dq __int_handle_125
    dq __int_handle_126
    dq __int_handle_127
    dq __int_handle_128
    dq __int_handle_129
    dq __int_handle_130
    dq __int_handle_131
    dq __int_handle_132
    dq __int_handle_133
    dq __int_handle_134
    dq __int_handle_135
    dq __int_handle_136
    dq __int_handle_137
    dq __int_handle_138
    dq __int_handle_139
    dq __int_handle_140
    dq __int_handle_141
    dq __int_handle_142
    dq __int_handle_143
    dq __int_handle_144
    dq __int_handle_145
    dq __int_handle_146
    dq __int_handle_147
    dq __int_handle_148
    dq __int_handle_149
    dq __int_handle_150
    dq __int_handle_151
    dq __int_handle_152
    dq __int_handle_153
    dq __int_handle_154
    dq __int_handle_155
    dq __int_handle_156
    dq __int_handle_157
    dq __int_handle_158
    dq __int_handle_159
    dq __int_handle_160
    dq __int_handle_161
    dq __int_handle_162
    dq __int_handle_163
    dq __int_handle_164
    dq __int_handle_165
    dq __int_handle_166
    dq __int_handle_167
    dq __int_handle_168
    dq __int_handle_169
    dq __int_handle_170
    dq __int_handle_171
    dq __int_handle_172
    dq __int_handle_173
    dq __int_handle_174
    dq __int_handle_175
    dq __int_handle_176
    dq __int_handle_177
    dq __int_handle_178
    dq __int_handle_179
    dq __int_handle_180
    dq __int_handle_181
    dq __int_handle_182
    dq __int_handle_183
    dq __int_handle_184
    dq __int_handle_185
    dq __int_handle_186
    dq __int_handle_187
    dq __int_handle_188
    dq __int_handle_189
    dq __int_handle_190
    dq __int_handle_191
    dq __int_handle_192
    dq __int_handle_193
    dq __int_handle_194
    dq __int_handle_195
    dq __int_handle_196
    dq __int_handle_197
    dq __int_handle_198
    dq __int_handle_199
    dq __int_handle_200
    dq __int_handle_201
    dq __int_handle_202
    dq __int_handle_203
    dq __int_handle_204
    dq __int_handle_205
    dq __int_handle_206
    dq __int_handle_207
    dq __int_handle_208
    dq __int_handle_209
    dq __int_handle_210
    dq __int_handle_211
    dq __int_handle_212
    dq __int_handle_213
    dq __int_handle_214
    dq __int_handle_215
    dq __int_handle_216
    dq __int_handle_217
    dq __int_handle_218
    dq __int_handle_219
    dq __int_handle_220
    dq __int_handle_221
    dq __int_handle_222
    dq __int_handle_223
    dq __int_handle_224
    dq __int_handle_225
    dq __int_handle_226
    dq __int_handle_227
    dq __int_handle_228
    dq __int_handle_229
    dq __int_handle_230
    dq __int_handle_231
    dq __int_handle_232
    dq __int_handle_233
    dq __int_handle_234
    dq __int_handle_235
    dq __int_handle_236
    dq __int_handle_237
    dq __int_handle_238
    dq __int_handle_239
    dq __int_handle_240
    dq __int_handle_241
    dq __int_handle_242
    dq __int_handle_243
    dq __int_handle_244
    dq __int_handle_245
    dq __int_handle_246
    dq __int_handle_247
    dq __int_handle_248
    dq __int_handle_249
    dq __int_handle_250
    dq __int_handle_251
    dq __int_handle_252
    dq __int_handle_253
    dq __int_handle_254
    dq __int_handle_255

